@host = https://localhost:45388
@endpoint = {{host}}/responses

### Health Check
GET {{host}}/readiness

### Simple prompt
POST {{endpoint}}
Content-Type: application/json

{
  "input": "Show me the list to do"
}

### Detailed prompt
POST {{endpoint}}
Content-Type: application/json

{
  "input": [
    {
      "type": "message",
      "role": "user",
      "content": [
        {
          "type": "input_text",
          "text": "Add workout at 7pm"
        }
      ]
    }
  ]
}
